# Generated by Django 5.1.6 on 2025-03-03 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dock_sn', models.CharField(max_length=100, verbose_name='机场SN')),
                ('drone_sn', models.CharField(max_length=100, verbose_name='无人机SN')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('height', models.FloatField(verbose_name='高度')),
                ('elevation', models.FloatField(verbose_name='相对起飞点高度')),
                ('horizontal_speed', models.FloatField(verbose_name='水平速度')),
                ('vertical_speed', models.FloatField(verbose_name='垂直速度')),
                ('attitude_pitch', models.FloatField(verbose_name='俯仰轴角度')),
                ('attitude_roll', models.FloatField(verbose_name='横滚轴角度')),
                ('attitude_head', models.FloatField(verbose_name='机头朝向角度')),
                ('capacity_percent', models.FloatField(verbose_name='电池电量')),
                ('dock_status', models.IntegerField(choices=[(0, '空闲中'), (1, '现场调试'), (2, '远程调试'), (3, '固件升级中'), (4, '作业中'), (-1, '离线')], verbose_name='设备状态')),
                ('gimbal_yaw', models.FloatField(verbose_name='云台偏航轴角度')),
                ('zoom_factor', models.IntegerField(verbose_name='云台变焦倍数')),
                ('gimbal_pitch', models.FloatField(verbose_name='云台俯仰轴角度')),
                ('time_stamp', models.BigIntegerField(verbose_name='时间戳')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '无人机',
                'verbose_name_plural': '无人机管理',
                'indexes': [models.Index(fields=['drone_sn'], name='polls_drone_drone_s_645b33_idx'), models.Index(fields=['dock_status'], name='polls_drone_dock_st_e28c9f_idx'), models.Index(fields=['time_stamp'], name='polls_drone_time_st_861510_idx')],
            },
        ),
    ]
