# Generated by Django 5.1.6 on 2025-03-04 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_missionassignment_missiontarget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drone',
            name='polls_drone_drone_s_645b33_idx',
        ),
        migrations.AddField(
            model_name='drone',
            name='drone_id',
            field=models.CharField(default=1, max_length=100, verbose_name='无人机ID'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(fields=['drone_id'], name='polls_drone_drone_i_47ba12_idx'),
        ),
    ]
