# Generated by Django 5.1.6 on 2025-03-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_drone_polls_drone_drone_s_645b33_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionassignment',
            options={'ordering': ['-start_time'], 'verbose_name': '任务分配', 'verbose_name_plural': '任务分配管理'},
        ),
        migrations.AlterModelOptions(
            name='missiontarget',
            options={'verbose_name': '任务目标', 'verbose_name_plural': '任务目标管理'},
        ),
        migrations.AddIndex(
            model_name='missiontarget',
            index=models.Index(fields=['name'], name='polls_missi_name_2fb029_idx'),
        ),
    ]
