# Generated by Django 5.1.6 on 2025-03-06 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_missionassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drone',
            name='polls_drone_drone_i_47ba12_idx',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='drone_id',
        ),
        migrations.AddField(
            model_name='drone',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='设备名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionassignment',
            name='status',
            field=models.IntegerField(choices=[(0, '待执行'), (1, '执行中'), (2, '已完成'), (3, '已失败')], default=0, verbose_name='任务状态'),
        ),
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(fields=['id'], name='polls_drone_id_309853_idx'),
        ),
        migrations.AddIndex(
            model_name='drone',
            index=models.Index(fields=['name'], name='polls_drone_name_b1bc3b_idx'),
        ),
    ]
