# Generated by Django 5.1.7 on 2025-03-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_drone_polls_drone_drone_i_47ba12_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontarget',
            name='altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='海拔高度'),
        ),
        migrations.AlterField(
            model_name='missiontarget',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='missiontarget',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
    ]
