# Generated by Django 5.1.7 on 2025-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_missiontarget_altitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionassignment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='missions/thumbs/%Y/%m/%d/', verbose_name='视频缩略图'),
        ),
        migrations.AlterField(
            model_name='missionassignment',
            name='video_recording',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='missions/videos/%Y/%m/%d/', verbose_name='任务录像'),
        ),
    ]
