# Generated by Django 5.1.7 on 2025-03-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_missionassignment_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='app_id',
            field=models.CharField(default=1, max_length=100, verbose_name='appid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drone',
            name='app_secret',
            field=models.CharField(default=1, max_length=100, verbose_name='appsecret'),
            preserve_default=False,
        ),
    ]
