# Generated by Django 5.1.7 on 2025-03-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_drone_app_id_drone_app_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='WayPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('height', models.FloatField(verbose_name='高度')),
                ('elevation', models.FloatField(verbose_name='相对起飞点高度')),
                ('horizontal_speed', models.FloatField(verbose_name='水平速度')),
                ('vertical_speed', models.FloatField(verbose_name='垂直速度')),
                ('attitude_pitch', models.FloatField(verbose_name='俯仰轴角度')),
                ('attitude_roll', models.FloatField(verbose_name='横滚轴角度')),
                ('attitude_head', models.FloatField(verbose_name='机头朝向角度')),
                ('sequence', models.PositiveIntegerField(verbose_name='航点序号')),
                ('is_reached', models.BooleanField(default=False, verbose_name='是否已到达')),
                ('reached_at', models.DateTimeField(blank=True, null=True, verbose_name='到达时间')),
                ('gimbal_yaw', models.FloatField(blank=True, null=True, verbose_name='云台偏航轴角度')),
                ('gimbal_pitch', models.FloatField(blank=True, help_text='-90到0度', null=True, verbose_name='云台俯仰轴角度')),
                ('zoom_factor', models.IntegerField(blank=True, null=True, verbose_name='云台变焦倍数')),
                ('take_photo', models.BooleanField(default=False, verbose_name='拍照')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='polls.drone')),
                ('mission_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='polls.missionassignment')),
            ],
            options={
                'verbose_name': '航点',
                'verbose_name_plural': '航点管理',
                'ordering': ['mission_assignment', 'sequence'],
                'indexes': [models.Index(fields=['mission_assignment', 'sequence'], name='polls_waypo_mission_7cedc3_idx'), models.Index(fields=['longitude', 'latitude'], name='polls_waypo_longitu_efa942_idx')],
                'constraints': [models.UniqueConstraint(fields=('mission_assignment', 'sequence'), name='unique_waypoint_sequence')],
            },
        ),
    ]
