# Generated by Django 5.1.7 on 2025-03-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_waypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missiontarget',
            name='drones',
        ),
        migrations.AddField(
            model_name='drone',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drones', to='polls.missionassignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionassignment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='任务名称'),
        ),
        migrations.AddField(
            model_name='missiontarget',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='polls.missionassignment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='drone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='polls.drone'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='mission_assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='polls.missionassignment'),
        ),
    ]
