# Generated by Django 5.1.7 on 2025-03-11 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_missiontarget_drones_drone_mission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='take_photo',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='missions/thumbs/%Y/%m/%d/', verbose_name='航点图片'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='polls.drone'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='mission_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='polls.missionassignment'),
        ),
    ]
