# Generated by Django 5.1.7 on 2025-03-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_waypoint_take_photo_waypoint_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionassignment',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='polls.missiontarget'),
        ),
    ]
