# Generated by Django 5.1.7 on 2025-03-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_missionassignment_target'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='missionassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='missionassignment',
            name='drone',
        ),
        migrations.RemoveField(
            model_name='missionassignment',
            name='target',
        ),
    ]
