# Generated by Django 5.1.7 on 2025-03-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_missionassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missiontarget',
            name='mission',
        ),
        migrations.AddField(
            model_name='missionassignment',
            name='target',
            field=models.ManyToManyField(related_name='assignments', to='polls.missiontarget'),
        ),
    ]
