# Generated by Django 5.1.7 on 2025-03-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_remove_missiontarget_mission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='mission',
            new_name='assignments',
        ),
    ]
