# Generated by Django 5.1.7 on 2025-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_rename_mission_drone_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionassignment',
            name='target',
            field=models.ManyToManyField(blank=True, related_name='assigned_missions', to='polls.missiontarget'),
        ),
    ]
