# Generated by Django 5.1.7 on 2025-03-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_missionassignment_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionassignment',
            old_name='target',
            new_name='targets',
        ),
    ]
