# Generated by Django 5.1.7 on 2025-03-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_rename_target_missionassignment_targets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='assignments',
        ),
        migrations.AddField(
            model_name='drone',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='assigned_drones', to='polls.missionassignment', verbose_name='任务分配'),
        ),
    ]
