# Generated by Django 5.1.7 on 2025-03-12 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_waypoint_mission_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='assignments',
        ),
        migrations.AddField(
            model_name='drone',
            name='assignments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drones', to='polls.missionassignment'),
            preserve_default=False,
        ),
    ]
