# Generated by Django 5.1.7 on 2025-03-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_remove_drone_assignments_drone_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionassignment',
            name='targets',
        ),
        migrations.AddField(
            model_name='missiontarget',
            name='missions',
            field=models.ManyToManyField(blank=True, related_name='targets', to='polls.missionassignment'),
        ),
    ]
